markdown: kramdown
name: ff4500
description: digital artist orange
encoding: utf-8

baseurl: ""
url: "https://ff4500.red"

collections:
    notes:
        output: true

    talks:
        output: true

    projects:
        output: true

exclude: ["sync.sh"]

layouts_dir: _jekyll/layouts
includes_dir: _jekyll/includes
