markdown: kramdown
name: ff4500
description: digital artist orange

baseurl: ""
url: "http://www.ff4500.red"
twitter_username: _xs

collections:
    projects:
        output: true
        permalink: /projects/:path

defaults:
    - 
        scope: 
            path: ""
            type: projects
        values:
            layout: post
            type: "digital work"
